version: '3.9'

services:
  mongo_db:
    container_name: mongodb_container_wallet
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Server API
  api:
    container_name: server_wallet
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 8082:8082
    environment:
      PORT: 8082
      MONGODB_URI: mongodb://mongo_db:27017
      MAX_BALANCE: 9900000000000
    depends_on:
      - mongo_db
  # UI
  ui:
    container_name: ui_wallet
    build:
      args:
        API_BASE: "${API_BASE}"
      dockerfile: Dockerfile
      context: ./ui
    ports:
      - 3001:3001
    depends_on:
      - mongo_db
      - api

volumes:
  mongo_db: {}
