version: '3.9'

services:
  mongo_db:
    container_name: mongodb_container_highlevel
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # server api
  api:
    build: .
    ports:
      - 8082:8082
    volumes:
      - /usr/src/app
    environment:
      PORT: 8082
      MONGODB_URI: mongodb://mongo_db:27017
      MAX_BALANCE: 9900000000000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
